name: Rust 

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/cargo@v1
      with:
        command: build
        args: --all-features
        toolchain: stable
        target: x86_64-unknown-linux-gnu
    - uses: actions-rs/cargo@v1
      with:
        command: test
        args: --all-features
        toolchain: stable
        target: x86_64-unknown-linux-gnu
